#!/bin/bash
#######################################################
# use for sync project on CentOS 7
# nodemon will update change for testing
#USE
#
# sh /var/www/html/gitsync
#
#######################################################

# NOTE PhpStorm, file end line LF (Linux)

#override all local file
git fetch origin
git reset --hard origin/master
#nodemon will update change...