#!/bin/bash
#######################################################
# use for sync project on CentOS 7
# nodemon will update change for testing
#USE
#
# cd /var/www/html; bash gitsync
#
#######################################################

# NOTE PhpStorm, file end line LF (Linux)

#override all local file
git fetch origin
git reset --hard origin/master
#nodemon will update change...